use regex::Regex;
use std::collections::{BTreeSet, HashMap};
use std::fs;
use std::path::Path;

#[derive(Debug, Clone, Default)]
pub struct BindgenOptions {
    pub library: Option<String>,
    pub link_kind: Option<String>,
}

#[derive(Debug, Clone)]
struct GeneratedConst {
    name: String,
    value: String,
}

#[derive(Debug, Clone)]
enum GeneratedAggregateKind {
    Struct,
    Union,
}

#[derive(Debug, Clone)]
struct GeneratedAggregate {
    kind: GeneratedAggregateKind,
    name: String,
    fields: Vec<(String, String)>,
}

#[derive(Debug, Clone)]
struct GeneratedExtern {
    name: String,
    params: Vec<(String, String)>,
    return_type: String,
}

pub fn generate_bindings(header_path: &Path, options: &BindgenOptions) -> Result<String, String> {
    let source =
        fs::read_to_string(header_path).map_err(|e| format!("cool bindgen: {}: {e}", header_path.display()))?;
    let stripped = strip_comments(&source);

    let mut notes = vec![
        format!("# Generated by cool bindgen from {}", header_path.display()),
        "# Review pointer ownership/lifetime metadata before shipping FFI APIs.".to_string(),
    ];

    let mut aliases = parse_simple_typedefs(&stripped);
    let mut consts = parse_defines(&stripped);
    consts.extend(parse_enums(&stripped, &mut notes));
    let aggregates = parse_aggregates(&stripped, &aliases, &mut notes);

    for aggregate in &aggregates {
        aliases.insert(aggregate.name.clone(), aggregate.name.clone());
    }

    let functions = parse_function_prototypes(&stripped, &aliases, &mut notes);
    let mut rendered = String::new();

    for note in dedup_lines(notes) {
        rendered.push_str(&note);
        rendered.push('\n');
    }
    rendered.push('\n');

    let mut seen_consts = BTreeSet::new();
    for item in consts {
        if seen_consts.insert(item.name.clone()) {
            rendered.push_str(&format!("const {} = {}\n", sanitize_ident(&item.name), item.value));
        }
    }
    if !seen_consts.is_empty() {
        rendered.push('\n');
    }

    for aggregate in aggregates {
        let keyword = match aggregate.kind {
            GeneratedAggregateKind::Struct => "struct",
            GeneratedAggregateKind::Union => "union",
        };
        rendered.push_str(&format!("{keyword} {}:\n", sanitize_ident(&aggregate.name)));
        if aggregate.fields.is_empty() {
            rendered.push_str("    pass\n");
        } else {
            for (field_name, field_type) in aggregate.fields {
                rendered.push_str(&format!("    {}: {}\n", sanitize_ident(&field_name), field_type));
            }
        }
        rendered.push('\n');
    }

    for function in functions {
        rendered.push_str(&format!("extern def {}(", sanitize_ident(&function.name)));
        for (idx, (name, ty)) in function.params.iter().enumerate() {
            if idx > 0 {
                rendered.push_str(", ");
            }
            rendered.push_str(&format!("{}: {}", sanitize_ident(name), ty));
        }
        rendered.push_str(&format!(") -> {}:\n", function.return_type));
        rendered.push_str("    cc: \"c\"\n");
        rendered.push_str(&format!("    symbol: \"{}\"\n", function.name));
        if let Some(library) = options.library.as_deref().filter(|value| !value.trim().is_empty()) {
            rendered.push_str(&format!("    library: \"{}\"\n", escape_string(library)));
        }
        if let Some(link_kind) = options.link_kind.as_deref().filter(|value| !value.trim().is_empty()) {
            rendered.push_str(&format!("    link_kind: \"{}\"\n", escape_string(link_kind)));
        }
        rendered.push('\n');
    }

    if rendered.trim().is_empty() {
        rendered.push_str("# No bindable declarations found.\n");
    }

    Ok(rendered)
}

fn dedup_lines(lines: Vec<String>) -> Vec<String> {
    let mut seen = BTreeSet::new();
    let mut out = Vec::new();
    for line in lines {
        if seen.insert(line.clone()) {
            out.push(line);
        }
    }
    out
}

fn escape_string(text: &str) -> String {
    text.replace('\\', "\\\\").replace('"', "\\\"")
}

fn strip_comments(source: &str) -> String {
    let mut out = String::with_capacity(source.len());
    let chars: Vec<char> = source.chars().collect();
    let mut i = 0usize;
    while i < chars.len() {
        let ch = chars[i];
        if ch == '"' {
            out.push(ch);
            i += 1;
            while i < chars.len() {
                out.push(chars[i]);
                if chars[i] == '\\' && i + 1 < chars.len() {
                    i += 1;
                    out.push(chars[i]);
                } else if chars[i] == '"' {
                    i += 1;
                    break;
                }
                i += 1;
            }
            continue;
        }
        if ch == '\'' {
            out.push(ch);
            i += 1;
            while i < chars.len() {
                out.push(chars[i]);
                if chars[i] == '\\' && i + 1 < chars.len() {
                    i += 1;
                    out.push(chars[i]);
                } else if chars[i] == '\'' {
                    i += 1;
                    break;
                }
                i += 1;
            }
            continue;
        }
        if ch == '/' && i + 1 < chars.len() && chars[i + 1] == '/' {
            while i < chars.len() && chars[i] != '\n' {
                i += 1;
            }
            continue;
        }
        if ch == '/' && i + 1 < chars.len() && chars[i + 1] == '*' {
            i += 2;
            while i + 1 < chars.len() && !(chars[i] == '*' && chars[i + 1] == '/') {
                i += 1;
            }
            i = (i + 2).min(chars.len());
            continue;
        }
        out.push(ch);
        i += 1;
    }
    out
}

fn parse_defines(source: &str) -> Vec<GeneratedConst> {
    let define_re = Regex::new(r#"(?m)^\s*#\s*define\s+([A-Za-z_][A-Za-z0-9_]*)\s+(.+?)\s*$"#).unwrap();
    let mut out = Vec::new();
    for captures in define_re.captures_iter(source) {
        let name = captures[1].to_string();
        let raw_value = captures[2].trim();
        if raw_value.contains('(') || raw_value.contains('\\') {
            continue;
        }
        if let Some(value) = parse_constant_expr(raw_value, &HashMap::new()) {
            out.push(GeneratedConst { name, value });
        }
    }
    out
}

fn parse_enums(source: &str, notes: &mut Vec<String>) -> Vec<GeneratedConst> {
    let enum_re = Regex::new(
        r#"(?s)(?:typedef\s+)?enum\s*([A-Za-z_][A-Za-z0-9_]*)?\s*\{(.*?)\}\s*([A-Za-z_][A-Za-z0-9_]*)?\s*;"#,
    )
    .unwrap();
    let mut out = Vec::new();
    for captures in enum_re.captures_iter(source) {
        let body = captures[2].trim();
        let mut values = HashMap::<String, i64>::new();
        let mut next_value = 0i64;
        for item in body.split(',') {
            let entry = item.trim();
            if entry.is_empty() {
                continue;
            }
            let (name, expr) = match entry.split_once('=') {
                Some((name, expr)) => (name.trim(), Some(expr.trim())),
                None => (entry, None),
            };
            let Some(name) = sanitize_ident_optional(name) else {
                continue;
            };
            let value = match expr {
                Some(expr) => match parse_int_expr(expr, &values) {
                    Some(value) => value,
                    None => {
                        notes.push(format!(
                            "# Skipped enum value '{name}': unsupported expression '{expr}'"
                        ));
                        continue;
                    }
                },
                None => next_value,
            };
            values.insert(name.clone(), value);
            out.push(GeneratedConst {
                name,
                value: value.to_string(),
            });
            next_value = value.saturating_add(1);
        }
    }
    out
}

fn parse_aggregates(
    source: &str,
    aliases: &HashMap<String, String>,
    notes: &mut Vec<String>,
) -> Vec<GeneratedAggregate> {
    let aggregate_re = Regex::new(
        r#"(?s)(?:typedef\s+)?(struct|union)\s*([A-Za-z_][A-Za-z0-9_]*)?\s*\{(.*?)\}\s*([A-Za-z_][A-Za-z0-9_]*)?\s*;"#,
    )
    .unwrap();
    let mut out = Vec::new();
    for captures in aggregate_re.captures_iter(source) {
        let kind = match &captures[1] {
            "struct" => GeneratedAggregateKind::Struct,
            "union" => GeneratedAggregateKind::Union,
            _ => continue,
        };
        let name = captures
            .get(4)
            .or_else(|| captures.get(2))
            .map(|value| value.as_str())
            .and_then(sanitize_ident_optional);
        let Some(name) = name else {
            continue;
        };
        let body = captures[3].trim();
        let mut fields = Vec::new();
        let mut skip_reason = None::<String>;
        for raw_field in body.split(';') {
            let field = raw_field.trim();
            if field.is_empty() {
                continue;
            }
            match parse_struct_field(field, aliases) {
                Ok(Some(parsed)) => fields.push(parsed),
                Ok(None) => {}
                Err(reason) => {
                    skip_reason = Some(reason);
                    break;
                }
            }
        }
        if let Some(reason) = skip_reason {
            notes.push(format!("# Skipped {name}: {reason}"));
            continue;
        }
        out.push(GeneratedAggregate { kind, name, fields });
    }
    out
}

fn parse_simple_typedefs(source: &str) -> HashMap<String, String> {
    let typedef_re = Regex::new(r#"(?m)^\s*typedef\s+([^;{}()]+?)\s+([A-Za-z_][A-Za-z0-9_]*)\s*;\s*$"#).unwrap();
    let mut out = HashMap::new();
    for captures in typedef_re.captures_iter(source) {
        out.insert(captures[2].trim().to_string(), normalize_type_text(captures[1].trim()));
    }
    out
}

fn parse_function_prototypes(
    source: &str,
    aliases: &HashMap<String, String>,
    notes: &mut Vec<String>,
) -> Vec<GeneratedExtern> {
    let mut cleaned = blank_block_bodies(source);
    cleaned = cleaned
        .lines()
        .filter(|line| !line.trim_start().starts_with('#'))
        .collect::<Vec<_>>()
        .join("\n");
    let mut out = Vec::new();
    for statement in cleaned.split(';') {
        let stmt = normalize_decl_text(statement);
        if stmt.is_empty() || stmt.starts_with("typedef ") {
            continue;
        }
        if !stmt.contains('(') || !stmt.contains(')') {
            continue;
        }
        if stmt.contains('{') || stmt.contains('}') || stmt.starts_with("struct ") || stmt.starts_with("union ") {
            continue;
        }
        let Some(open_paren) = stmt.find('(') else {
            continue;
        };
        let Some(close_paren) = stmt.rfind(')') else {
            continue;
        };
        let prefix = strip_decl_prefix(stmt[..open_paren].trim());
        let params_text = stmt[open_paren + 1..close_paren].trim();
        if prefix.is_empty() {
            continue;
        }
        let Some((name, return_type_raw)) = split_decl_name_and_type(prefix) else {
            notes.push(format!("# Skipped prototype '{}': unsupported declarator", stmt.trim()));
            continue;
        };
        let Some(return_type) = map_extern_type(&return_type_raw, aliases, false) else {
            notes.push(format!(
                "# Skipped prototype '{}': unsupported return type '{}'",
                name, return_type_raw
            ));
            continue;
        };
        let mut params = Vec::new();
        let mut supported = true;
        if params_text != "void" && !params_text.is_empty() {
            for (index, raw_param) in params_text.split(',').enumerate() {
                let raw_param = raw_param.trim();
                if raw_param == "..." {
                    notes.push(format!("# Skipped prototype '{}': varargs are not supported yet", name));
                    supported = false;
                    break;
                }
                match parse_function_param(raw_param, aliases, index) {
                    Ok((param_name, param_type)) => params.push((param_name, param_type)),
                    Err(reason) => {
                        notes.push(format!("# Skipped prototype '{}': {}", name, reason));
                        supported = false;
                        break;
                    }
                }
            }
        }
        if supported {
            out.push(GeneratedExtern {
                name,
                params,
                return_type,
            });
        }
    }
    out
}

fn blank_block_bodies(source: &str) -> String {
    let mut out = String::with_capacity(source.len());
    let mut depth = 0usize;
    for ch in source.chars() {
        match ch {
            '{' => {
                depth += 1;
                out.push(' ');
            }
            '}' => {
                depth = depth.saturating_sub(1);
                out.push(' ');
            }
            _ if depth > 0 => {
                if ch == '\n' {
                    out.push('\n');
                } else {
                    out.push(' ');
                }
            }
            _ => out.push(ch),
        }
    }
    out
}

fn parse_function_param(
    raw_param: &str,
    aliases: &HashMap<String, String>,
    index: usize,
) -> Result<(String, String), String> {
    let parsed = parse_declarator(raw_param, true).ok_or_else(|| format!("unsupported parameter '{}'", raw_param))?;
    let Some(mapped) = map_extern_type(&parsed.ty, aliases, parsed.is_array) else {
        return Err(format!("unsupported parameter type '{}'", parsed.ty));
    };
    let name = parsed.name.unwrap_or_else(|| format!("arg{index}")).trim().to_string();
    Ok((name, mapped))
}

fn parse_struct_field(raw_field: &str, aliases: &HashMap<String, String>) -> Result<Option<(String, String)>, String> {
    if raw_field.starts_with('#') {
        return Ok(None);
    }
    let parsed = parse_declarator(raw_field, false).ok_or_else(|| format!("unsupported field '{}'", raw_field))?;
    let name = parsed
        .name
        .ok_or_else(|| format!("field '{}' is missing a name", raw_field))?;
    let field_type = map_struct_field_type(&parsed.ty, aliases, parsed.is_array)
        .ok_or_else(|| format!("field '{}' has unsupported type '{}'", name, parsed.ty))?;
    Ok(Some((name, field_type)))
}

#[derive(Debug)]
struct ParsedDeclarator {
    ty: String,
    name: Option<String>,
    is_array: bool,
}

fn parse_declarator(raw: &str, arrays_decay_to_pointer: bool) -> Option<ParsedDeclarator> {
    if raw.contains("(*)") || raw.contains("(* ") {
        return None;
    }
    let text = normalize_decl_text(raw);
    if text.is_empty() {
        return None;
    }
    let array_re = Regex::new(r#"([A-Za-z_][A-Za-z0-9_]*)\s*\[[^\]]*\]\s*$"#).unwrap();
    if let Some(captures) = array_re.captures(&text) {
        let name = captures[1].to_string();
        let start = captures.get(1).unwrap().start();
        let ty = normalize_type_text(text[..start].trim());
        if ty.is_empty() {
            return None;
        }
        return Some(ParsedDeclarator {
            ty,
            name: Some(name),
            is_array: arrays_decay_to_pointer,
        });
    }
    let ident_re = Regex::new(r#"([A-Za-z_][A-Za-z0-9_]*)\s*$"#).unwrap();
    if let Some(captures) = ident_re.captures(&text) {
        let name = captures[1].to_string();
        let start = captures.get(1).unwrap().start();
        let ty = normalize_type_text(text[..start].trim());
        if !ty.is_empty() {
            return Some(ParsedDeclarator {
                ty,
                name: Some(name),
                is_array: false,
            });
        }
    }
    Some(ParsedDeclarator {
        ty: normalize_type_text(&text),
        name: None,
        is_array: false,
    })
}

fn normalize_decl_text(text: &str) -> String {
    normalize_type_text(
        &text
            .replace('\n', " ")
            .replace('\r', " ")
            .replace('\t', " ")
            .replace(" ,", ",")
            .replace("( ", "(")
            .replace(" )", ")"),
    )
}

fn normalize_type_text(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn strip_decl_prefix(text: &str) -> String {
    let mut out = text.to_string();
    let attribute_re = Regex::new(r#"__attribute__\s*\(\(.*?\)\)"#).unwrap();
    let declspec_re = Regex::new(r#"__declspec\s*\(.*?\)"#).unwrap();
    out = attribute_re.replace_all(&out, " ").to_string();
    out = declspec_re.replace_all(&out, " ").to_string();
    loop {
        let trimmed = out.trim_start();
        let next = [
            "extern ",
            "static ",
            "inline ",
            "__inline ",
            "__inline__ ",
            "APIENTRY ",
            "WINAPI ",
            "CALLBACK ",
        ]
        .into_iter()
        .find_map(|prefix| trimmed.strip_prefix(prefix).map(str::to_string));
        match next {
            Some(value) => out = value,
            None => break,
        }
    }
    normalize_type_text(&out)
}

fn split_decl_name_and_type(prefix: String) -> Option<(String, String)> {
    let parsed = parse_declarator(&prefix, false)?;
    let name = parsed.name?;
    Some((name, parsed.ty))
}

fn resolve_alias(mut base: String, aliases: &HashMap<String, String>) -> String {
    let mut seen = BTreeSet::new();
    while seen.insert(base.clone()) {
        let Some(next) = aliases.get(&base) else {
            break;
        };
        base = next.clone();
    }
    base
}

fn map_extern_type(raw: &str, aliases: &HashMap<String, String>, is_array: bool) -> Option<String> {
    let parsed = parse_c_type(raw, aliases);
    if parsed.is_function_pointer {
        return None;
    }
    if parsed.pointer_depth > 0 || is_array {
        if parsed.base == "char" || parsed.base == "signed char" || parsed.base == "unsigned char" {
            return Some("str".to_string());
        }
        return Some("ptr".to_string());
    }
    if parsed.base == "void" {
        return Some("void".to_string());
    }
    map_scalar_type(&parsed.base, true)
}

fn map_struct_field_type(raw: &str, aliases: &HashMap<String, String>, is_array: bool) -> Option<String> {
    let parsed = parse_c_type(raw, aliases);
    if parsed.is_function_pointer {
        return None;
    }
    if parsed.pointer_depth > 0 || is_array {
        return Some("usize".to_string());
    }
    if let Some(mapped) = map_scalar_type(&parsed.base, false) {
        return Some(mapped);
    }
    if parsed.base.starts_with("struct ") || parsed.base.starts_with("union ") {
        return parsed.base.split_whitespace().nth(1).and_then(sanitize_ident_optional);
    }
    sanitize_ident_optional(&parsed.base)
}

fn map_scalar_type(base: &str, allow_void: bool) -> Option<String> {
    Some(
        match base {
            "void" if allow_void => "void",
            "bool" | "_Bool" => "u8",
            "char" | "signed char" => "i8",
            "unsigned char" => "u8",
            "short" | "short int" | "signed short" | "signed short int" | "int16_t" => "i16",
            "unsigned short" | "unsigned short int" | "uint16_t" => "u16",
            "int" | "signed" | "signed int" | "int32_t" => "i32",
            "unsigned" | "unsigned int" | "uint32_t" => "u32",
            "long" | "long int" | "signed long" | "signed long int" | "intptr_t" | "ssize_t" | "ptrdiff_t" => "isize",
            "unsigned long" | "unsigned long int" | "uintptr_t" | "size_t" => "usize",
            "long long" | "long long int" | "signed long long" | "signed long long int" | "int64_t" => "i64",
            "unsigned long long" | "unsigned long long int" | "uint64_t" => "u64",
            "float" => "f32",
            "double" => "f64",
            "enum" => "i32",
            other if other.starts_with("enum ") => "i32",
            _ => return None,
        }
        .to_string(),
    )
}

#[derive(Debug)]
struct ParsedCType {
    base: String,
    pointer_depth: usize,
    is_function_pointer: bool,
}

fn parse_c_type(raw: &str, aliases: &HashMap<String, String>) -> ParsedCType {
    let mut text = normalize_type_text(raw);
    let is_function_pointer = text.contains("(*)");
    let pointer_depth = text.chars().filter(|&ch| ch == '*').count();
    text = text.replace('*', " ");
    let tokens = text
        .split_whitespace()
        .filter(|token| {
            !matches!(
                *token,
                "const" | "volatile" | "restrict" | "__restrict" | "__restrict__"
            )
        })
        .map(str::to_string)
        .collect::<Vec<_>>();
    if tokens.is_empty() {
        return ParsedCType {
            base: "void".to_string(),
            pointer_depth,
            is_function_pointer,
        };
    }
    let mut base = normalize_type_text(&tokens.join(" "));
    if !base.starts_with("struct ") && !base.starts_with("union ") && !base.starts_with("enum ") {
        base = resolve_alias(base, aliases);
    }
    if base == "signed" {
        base = "signed int".to_string();
    } else if base == "unsigned" {
        base = "unsigned int".to_string();
    }
    ParsedCType {
        base,
        pointer_depth,
        is_function_pointer,
    }
}

fn parse_constant_expr(expr: &str, scope: &HashMap<String, i64>) -> Option<String> {
    let trimmed = expr.trim();
    if let Some(text) = parse_string_literal(trimmed) {
        return Some(format!("\"{}\"", escape_string(&text)));
    }
    parse_int_expr(trimmed, scope).map(|value| value.to_string())
}

fn parse_string_literal(raw: &str) -> Option<String> {
    if raw.len() >= 2 && raw.starts_with('"') && raw.ends_with('"') {
        return Some(raw[1..raw.len() - 1].to_string());
    }
    None
}

fn parse_int_expr(expr: &str, scope: &HashMap<String, i64>) -> Option<i64> {
    let trimmed = expr.trim();
    if let Some(value) = parse_int_literal(trimmed) {
        return Some(value);
    }
    if let Some(value) = scope.get(trimmed) {
        return Some(*value);
    }
    if let Some(rest) = trimmed.strip_prefix('-') {
        return parse_int_expr(rest, scope).map(|value| value.saturating_neg());
    }
    if let Some(rest) = trimmed.strip_prefix('+') {
        return parse_int_expr(rest, scope);
    }
    for op in ["<<", ">>", "|", "&", "+", "-"] {
        if let Some(index) = find_expr_operator(trimmed, op) {
            let lhs = parse_int_expr(trimmed[..index].trim(), scope)?;
            let rhs = parse_int_expr(trimmed[index + op.len()..].trim(), scope)?;
            return match op {
                "<<" => Some(lhs.wrapping_shl(rhs as u32)),
                ">>" => Some(lhs.wrapping_shr(rhs as u32)),
                "|" => Some(lhs | rhs),
                "&" => Some(lhs & rhs),
                "+" => Some(lhs.saturating_add(rhs)),
                "-" => Some(lhs.saturating_sub(rhs)),
                _ => None,
            };
        }
    }
    None
}

fn find_expr_operator(expr: &str, operator: &str) -> Option<usize> {
    let mut depth = 0i32;
    let chars: Vec<char> = expr.chars().collect();
    let op_chars: Vec<char> = operator.chars().collect();
    let mut index = 0usize;
    while index + op_chars.len() <= chars.len() {
        match chars[index] {
            '(' => depth += 1,
            ')' => depth -= 1,
            _ => {}
        }
        if depth == 0 && chars[index..index + op_chars.len()] == op_chars[..] {
            if operator == "-"
                && (index == 0
                    || matches!(
                        chars[index.saturating_sub(1)],
                        '(' | '+' | '-' | '*' | '/' | '%' | '&' | '|' | '^' | '<' | '>'
                    ))
            {
                index += 1;
                continue;
            }
            return Some(index);
        }
        index += 1;
    }
    None
}

fn parse_int_literal(raw: &str) -> Option<i64> {
    let trimmed = raw
        .trim()
        .trim_end_matches(|ch: char| matches!(ch, 'u' | 'U' | 'l' | 'L'));
    if let Some(hex) = trimmed.strip_prefix("0x").or_else(|| trimmed.strip_prefix("0X")) {
        return i64::from_str_radix(hex, 16).ok();
    }
    if let Some(bin) = trimmed.strip_prefix("0b").or_else(|| trimmed.strip_prefix("0B")) {
        return i64::from_str_radix(bin, 2).ok();
    }
    trimmed.parse::<i64>().ok()
}

fn sanitize_ident_optional(raw: &str) -> Option<String> {
    let trimmed = raw.trim();
    if trimmed.is_empty() {
        None
    } else {
        Some(sanitize_ident(trimmed))
    }
}

fn sanitize_ident(raw: &str) -> String {
    let mut out = String::with_capacity(raw.len());
    for ch in raw.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() {
        out.push('_');
    }
    if out.chars().next().unwrap().is_ascii_digit() {
        out.insert(0, '_');
    }
    if matches!(
        out.as_str(),
        "and"
            | "as"
            | "break"
            | "class"
            | "const"
            | "continue"
            | "data"
            | "def"
            | "else"
            | "except"
            | "extern"
            | "false"
            | "finally"
            | "for"
            | "if"
            | "import"
            | "in"
            | "nil"
            | "not"
            | "or"
            | "packed"
            | "pass"
            | "private"
            | "public"
            | "return"
            | "struct"
            | "true"
            | "try"
            | "union"
            | "while"
    ) {
        out.push('_');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bindgen_generates_struct_consts_and_externs() {
        let header = r#"
            #define COOL_FLAG 4
            typedef struct point {
                int x;
                unsigned int y;
                void* ctx;
            } Point;

            enum mode {
                MODE_READ = 1,
                MODE_WRITE,
            };

            int add(int lhs, int rhs);
            const char* greet(const char* name);
        "#;

        let stripped = strip_comments(header);
        let mut notes = Vec::new();
        let mut aliases = parse_simple_typedefs(&stripped);
        let consts = parse_defines(&stripped);
        let enums = parse_enums(&stripped, &mut notes);
        let aggregates = parse_aggregates(&stripped, &aliases, &mut notes);
        for aggregate in &aggregates {
            aliases.insert(aggregate.name.clone(), aggregate.name.clone());
        }
        let externs = parse_function_prototypes(&stripped, &aliases, &mut notes);

        assert!(consts.iter().any(|item| item.name == "COOL_FLAG" && item.value == "4"));
        assert!(enums.iter().any(|item| item.name == "MODE_WRITE" && item.value == "2"));
        assert!(aggregates.iter().any(|item| {
            item.name == "Point"
                && item.fields
                    == vec![
                        ("x".to_string(), "i32".to_string()),
                        ("y".to_string(), "u32".to_string()),
                        ("ctx".to_string(), "usize".to_string()),
                    ]
        }));
        assert!(externs.iter().any(|item| {
            item.name == "add"
                && item.params
                    == vec![
                        ("lhs".to_string(), "i32".to_string()),
                        ("rhs".to_string(), "i32".to_string()),
                    ]
                && item.return_type == "i32"
        }));
        assert!(externs.iter().any(|item| {
            item.name == "greet"
                && item.params == vec![("name".to_string(), "str".to_string())]
                && item.return_type == "str"
        }));
    }
}
